[2025-05-12T18:52:12.484+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gold_news_pipeline.check_cassandra manual__2025-05-12T18:51:26.755940+00:00 [queued]>
[2025-05-12T18:52:12.496+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gold_news_pipeline.check_cassandra manual__2025-05-12T18:51:26.755940+00:00 [queued]>
[2025-05-12T18:52:12.497+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-12T18:52:12.526+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): check_cassandra> on 2025-05-12 18:51:26.755940+00:00
[2025-05-12T18:52:12.543+0000] {standard_task_runner.py:57} INFO - Started process 1285 to run task
[2025-05-12T18:52:12.544+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gold_news_pipeline', 'check_cassandra', 'manual__2025-05-12T18:51:26.755940+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/dag_news.py', '--cfg-path', '/tmp/tmp0ai3qfpq']
[2025-05-12T18:52:12.558+0000] {standard_task_runner.py:85} INFO - Job 118: Subtask check_cassandra
[2025-05-12T18:52:12.655+0000] {task_command.py:415} INFO - Running <TaskInstance: gold_news_pipeline.check_cassandra manual__2025-05-12T18:51:26.755940+00:00 [running]> on host 002c8bd4eccc
[2025-05-12T18:52:12.814+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gold_news_pipeline' AIRFLOW_CTX_TASK_ID='check_cassandra' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T18:51:26.755940+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-12T18:51:26.755940+00:00'
[2025-05-12T18:52:12.824+0000] {dag_news.py:49} WARNING - Cluster.__init__ called with contact_points specified, but no load_balancing_policy. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = ['cassandra'], lbp = None)
[2025-05-12T18:52:12.840+0000] {dag_news.py:50} WARNING - Downgrading core protocol version from 66 to 65 for 172.18.0.3:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2025-05-12T18:52:12.842+0000] {dag_news.py:50} WARNING - Downgrading core protocol version from 65 to 5 for 172.18.0.3:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2025-05-12T18:52:12.859+0000] {policies.py:289} INFO - Using datacenter 'DC1' for DCAwareRoundRobinPolicy (via host '172.18.0.3:9042'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
[2025-05-12T18:52:13.380+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-05-12T18:52:13.395+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_news.py", line 56, in check_cassandra_data
    result = session.execute(statement, [ingestion_time])
  File "cassandra/cluster.py", line 2637, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4920, in cassandra.cluster.ResponseFuture.result
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="table articles does not exist"
[2025-05-12T18:52:13.423+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=gold_news_pipeline, task_id=check_cassandra, execution_date=20250512T185126, start_date=20250512T185212, end_date=20250512T185213
[2025-05-12T18:52:13.452+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 118 for task check_cassandra (Error from server: code=2200 [Invalid query] message="table articles does not exist"; 1285)
[2025-05-12T18:52:13.527+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-12T18:52:13.555+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
