[2025-05-20T15:43:59.157+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: start_kafka_spark.verify_hdfs_data manual__2025-05-20T15:38:46.150966+00:00 [queued]>
[2025-05-20T15:43:59.171+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: start_kafka_spark.verify_hdfs_data manual__2025-05-20T15:38:46.150966+00:00 [queued]>
[2025-05-20T15:43:59.171+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-05-20T15:43:59.188+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): verify_hdfs_data> on 2025-05-20 15:38:46.150966+00:00
[2025-05-20T15:43:59.198+0000] {standard_task_runner.py:57} INFO - Started process 3087 to run task
[2025-05-20T15:43:59.203+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'start_kafka_spark', 'verify_hdfs_data', 'manual__2025-05-20T15:38:46.150966+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/streaming_lance.py', '--cfg-path', '/tmp/tmpnbb8q7xd']
[2025-05-20T15:43:59.206+0000] {standard_task_runner.py:85} INFO - Job 46: Subtask verify_hdfs_data
[2025-05-20T15:43:59.305+0000] {task_command.py:415} INFO - Running <TaskInstance: start_kafka_spark.verify_hdfs_data manual__2025-05-20T15:38:46.150966+00:00 [running]> on host 6bb1f84c11d3
[2025-05-20T15:43:59.457+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='start_kafka_spark' AIRFLOW_CTX_TASK_ID='verify_hdfs_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T15:38:46.150966+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T15:38:46.150966+00:00'
[2025-05-20T15:43:59.462+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-20T15:43:59.463+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            # Vérifier si des données existent dans HDFS pour aujourd\'hui\n            hdfs_output=$(docker exec -i namenode bash -c "hdfs dfs -ls /gold_price/aggregates/year=2025/month=5/day=20" 2>/dev/null)\n\n            if [ -n "$hdfs_output" ]; then\n                echo "Données HDFS présentes pour aujourd\'hui (2025-05-20)"\n                curl -X POST -H "Content-Type: application/json" -d \'{"content":"✅ Données HDFS présentes pour 2025-05-20 ! Pipeline fonctionne."}\'https://discord.com/api/webhooks/1374382502981931008/BRaqnl_BHNxEep-dItvMinlhhcd9Tk5-sj3RbKdG3qDzLjwfYGRze8IZTxRoaiQj0DE2\n            else\n                echo "Aucune donnée HDFS trouvée pour aujourd\'hui (2025-05-20)"\n                curl -X POST -H "Content-Type: application/json" -d \'{"content":"❌ Aucune donnée HDFS trouvée pour 2025-05-20. Vérifiez le pipeline."}\' https://discord.com/api/webhooks/1374382502981931008/BRaqnl_BHNxEep-dItvMinlhhcd9Tk5-sj3RbKdG3qDzLjwfYGRze8IZTxRoaiQj0DE2\n            fi\n        ']
[2025-05-20T15:43:59.478+0000] {subprocess.py:86} INFO - Output:
[2025-05-20T15:44:02.640+0000] {subprocess.py:93} INFO - Données HDFS présentes pour aujourd'hui (2025-05-20)
[2025-05-20T15:44:02.649+0000] {subprocess.py:93} INFO - curl: no URL specified!
[2025-05-20T15:44:02.650+0000] {subprocess.py:93} INFO - curl: try 'curl --help' or 'curl --manual' for more information
[2025-05-20T15:44:02.651+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-20T15:44:02.665+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-20T15:44:02.670+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=start_kafka_spark, task_id=verify_hdfs_data, execution_date=20250520T153846, start_date=20250520T154359, end_date=20250520T154402
[2025-05-20T15:44:02.686+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 46 for task verify_hdfs_data (Bash command failed. The command returned a non-zero exit code 2.; 3087)
[2025-05-20T15:44:02.723+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-20T15:44:02.745+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
