[2025-05-08T14:14:41.885+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gold_pipeline.load_gold_data manual__2025-05-08T14:13:59.977187+00:00 [queued]>
[2025-05-08T14:14:41.894+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gold_pipeline.load_gold_data manual__2025-05-08T14:13:59.977187+00:00 [queued]>
[2025-05-08T14:14:41.895+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-08T14:14:41.909+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_gold_data> on 2025-05-08 14:13:59.977187+00:00
[2025-05-08T14:14:41.914+0000] {standard_task_runner.py:57} INFO - Started process 6885 to run task
[2025-05-08T14:14:41.917+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gold_pipeline', 'load_gold_data', 'manual__2025-05-08T14:13:59.977187+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp9c440ydu']
[2025-05-08T14:14:41.920+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask load_gold_data
[2025-05-08T14:14:41.964+0000] {task_command.py:415} INFO - Running <TaskInstance: gold_pipeline.load_gold_data manual__2025-05-08T14:13:59.977187+00:00 [running]> on host 223a2d167166
[2025-05-08T14:14:42.035+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gold_pipeline' AIRFLOW_CTX_TASK_ID='load_gold_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T14:13:59.977187+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-08T14:13:59.977187+00:00'
[2025-05-08T14:14:42.058+0000] {logging_mixin.py:151} WARNING - TypeError: cannot construct a FileSource from <contextlib._GeneratorContextManager object at 0x7f4ebb480e80>
[2025-05-08T14:14:42.059+0000] {logging_mixin.py:151} WARNING - Exception ignored in: 'pyarrow._dataset._make_file_source'
[2025-05-08T14:14:42.059+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2025-05-08T14:14:42.060+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/pyarrow/parquet/core.py", line 2463, in __init__
[2025-05-08T14:14:42.061+0000] {logging_mixin.py:151} WARNING -     fragment = parquet_format.make_fragment(single_file, filesystem)
[2025-05-08T14:14:42.061+0000] {logging_mixin.py:151} WARNING - TypeError: cannot construct a FileSource from <contextlib._GeneratorContextManager object at 0x7f4ebb480e80>
[2025-05-08T14:14:42.063+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load.py", line 21, in load_gold_data
    fait_prix_or = pq.read_table(HDFS_CLIENT.read(f"/gold_datalake/processed/gold_prices_{today}.parquet")).to_pandas()
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/parquet/core.py", line 2926, in read_table
    dataset = _ParquetDatasetV2(
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/parquet/core.py", line 2466, in __init__
    [fragment], schema=schema or fragment.physical_schema,
  File "pyarrow/_dataset.pyx", line 1004, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Called Open() on an uninitialized FileSource
[2025-05-08T14:14:42.073+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=gold_pipeline, task_id=load_gold_data, execution_date=20250508T141359, start_date=20250508T141441, end_date=20250508T141442
[2025-05-08T14:14:42.084+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 40 for task load_gold_data (Called Open() on an uninitialized FileSource; 6885)
[2025-05-08T14:14:42.129+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-08T14:14:42.144+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
