[2025-05-08T13:35:52.554+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gold_pipeline.transform_gold_data manual__2025-05-08T13:35:26.522017+00:00 [queued]>
[2025-05-08T13:35:52.563+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gold_pipeline.transform_gold_data manual__2025-05-08T13:35:26.522017+00:00 [queued]>
[2025-05-08T13:35:52.563+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-08T13:35:52.576+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_gold_data> on 2025-05-08 13:35:26.522017+00:00
[2025-05-08T13:35:52.582+0000] {standard_task_runner.py:57} INFO - Started process 1977 to run task
[2025-05-08T13:35:52.586+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gold_pipeline', 'transform_gold_data', 'manual__2025-05-08T13:35:26.522017+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpyiq8svzc']
[2025-05-08T13:35:52.589+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask transform_gold_data
[2025-05-08T13:35:52.642+0000] {task_command.py:415} INFO - Running <TaskInstance: gold_pipeline.transform_gold_data manual__2025-05-08T13:35:26.522017+00:00 [running]> on host 223a2d167166
[2025-05-08T13:35:52.736+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gold_pipeline' AIRFLOW_CTX_TASK_ID='transform_gold_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T13:35:26.522017+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-08T13:35:26.522017+00:00'
[2025-05-08T13:35:52.738+0000] {client.py:724} INFO - Reading file '/gold_datalake/raw/gold_prices/2025-05-08.csv'.
[2025-05-08T13:35:52.825+0000] {client.py:724} INFO - Reading file '/gold_datalake/raw/fed_rates/2025-05-08.csv'.
[2025-05-08T13:35:52.849+0000] {client.py:724} INFO - Reading file '/gold_datalake/raw/sp500/2025-05-08.csv'.
[2025-05-08T13:35:52.898+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'prix_or'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/transform.py", line 58, in transform_gold_data
    merged_df["prix_or"] = merged_df["prix_or"].interpolate(method="linear")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'prix_or'
[2025-05-08T13:35:52.914+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=gold_pipeline, task_id=transform_gold_data, execution_date=20250508T133526, start_date=20250508T133552, end_date=20250508T133552
[2025-05-08T13:35:52.926+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task transform_gold_data ('prix_or'; 1977)
[2025-05-08T13:35:52.962+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-08T13:35:52.991+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
