[2025-05-20T17:37:09.968+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kill_running_scripts.check_spark_log_errors manual__2025-05-20T17:37:08.449188+00:00 [queued]>
[2025-05-20T17:37:09.980+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kill_running_scripts.check_spark_log_errors manual__2025-05-20T17:37:08.449188+00:00 [queued]>
[2025-05-20T17:37:09.980+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-20T17:37:09.999+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): check_spark_log_errors> on 2025-05-20 17:37:08.449188+00:00
[2025-05-20T17:37:10.007+0000] {standard_task_runner.py:57} INFO - Started process 511 to run task
[2025-05-20T17:37:10.012+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kill_running_scripts', 'check_spark_log_errors', 'manual__2025-05-20T17:37:08.449188+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/stoper_streaming.py', '--cfg-path', '/tmp/tmp8xkxk8h_']
[2025-05-20T17:37:10.015+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask check_spark_log_errors
[2025-05-20T17:37:10.079+0000] {task_command.py:415} INFO - Running <TaskInstance: kill_running_scripts.check_spark_log_errors manual__2025-05-20T17:37:08.449188+00:00 [running]> on host 6bb1f84c11d3
[2025-05-20T17:37:10.192+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kill_running_scripts' AIRFLOW_CTX_TASK_ID='check_spark_log_errors' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T17:37:08.449188+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T17:37:08.449188+00:00'
[2025-05-20T17:37:10.196+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-20T17:37:10.197+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            docker exec gold_price_project-spark-1 bash -c \'\n            if grep -i "error" /scripts/logs/spark.log; then\n                echo "❌ Erreur détectée, envoi de contexte à Discord..."\n                grep -i -B 20 -A 20 "error" /scripts/logs/spark.log > /tmp/spark_error_excerpt.log\n                ESCAPED=$(cat /tmp/spark_error_excerpt.log | sed "s/\\\\/\\\\\\\\/g" | sed "s/"/\\\\\\"/g" | sed "s/\'/\\\\\'/g" | head -c 1900)\n                curl -X POST -H "Content-Type: application/json" \\\n                     -d "{\\"content\\": \\"🚨 Erreur détectée dans spark.log à 00:00 :\\n\\n\\n$ESCAPED\\"}" \\\n                     https://discord.com/api/webhooks/1374382502981931008/BRaqnl_BHNxEep-dItvMinlhhcd9Tk5-sj3RbKdG3qDzLjwfYGRze8IZTxRoaiQj0DE2\n            else\n                echo "✅ Aucun problème détecté dans spark.log"\n            fi\n\n            # Nettoyer le fichier après envoi\n            echo "" > /scripts/logs/spark.log\n            \'\n        ']
[2025-05-20T17:37:10.214+0000] {subprocess.py:86} INFO - Output:
[2025-05-20T17:37:10.312+0000] {subprocess.py:93} INFO - bash: -c: line 13: unexpected EOF while looking for matching `"'
[2025-05-20T17:37:10.316+0000] {subprocess.py:93} INFO - bash: -c: line 15: syntax error: unexpected end of file
[2025-05-20T17:37:10.323+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-20T17:37:10.337+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-20T17:37:10.341+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=kill_running_scripts, task_id=check_spark_log_errors, execution_date=20250520T173708, start_date=20250520T173709, end_date=20250520T173710
[2025-05-20T17:37:10.361+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 60 for task check_spark_log_errors (Bash command failed. The command returned a non-zero exit code 1.; 511)
[2025-05-20T17:37:10.385+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-20T17:37:10.426+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
