[2025-05-12T18:01:33.651+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gold_news_pipeline.run_consumer scheduled__2025-05-12T17:51:18.013350+00:00 [queued]>
[2025-05-12T18:01:33.665+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gold_news_pipeline.run_consumer scheduled__2025-05-12T17:51:18.013350+00:00 [queued]>
[2025-05-12T18:01:33.665+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-12T18:01:33.681+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): run_consumer> on 2025-05-12 17:51:18.013350+00:00
[2025-05-12T18:01:33.689+0000] {standard_task_runner.py:57} INFO - Started process 223 to run task
[2025-05-12T18:01:33.693+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gold_news_pipeline', 'run_consumer', 'scheduled__2025-05-12T17:51:18.013350+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/dag_news.py', '--cfg-path', '/tmp/tmpyr08t2_h']
[2025-05-12T18:01:33.696+0000] {standard_task_runner.py:85} INFO - Job 96: Subtask run_consumer
[2025-05-12T18:01:33.756+0000] {task_command.py:415} INFO - Running <TaskInstance: gold_news_pipeline.run_consumer scheduled__2025-05-12T17:51:18.013350+00:00 [running]> on host c26e5a949b49
[2025-05-12T18:01:33.870+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gold_news_pipeline' AIRFLOW_CTX_TASK_ID='run_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T17:51:18.013350+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-12T17:51:18.013350+00:00'
[2025-05-12T18:01:33.873+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-12T18:01:33.874+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec gold_price_project-spark-1 spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,com.datastax.spark:spark-cassandra-connector_2.12:3.5.0 /scripts/spark_news.py']
[2025-05-12T18:01:33.892+0000] {subprocess.py:86} INFO - Output:
[2025-05-12T18:01:33.950+0000] {subprocess.py:93} INFO - Error response from daemon: container dedf70ba0687bf7646d92df7c82b5a7bdc9c5cee72d58de48d74e8466806abbd is not running
[2025-05-12T18:01:33.951+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-12T18:01:33.968+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-12T18:01:33.976+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=gold_news_pipeline, task_id=run_consumer, execution_date=20250512T175118, start_date=20250512T180133, end_date=20250512T180133
[2025-05-12T18:01:34.010+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 96 for task run_consumer (Bash command failed. The command returned a non-zero exit code 1.; 223)
[2025-05-12T18:01:34.067+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-12T18:01:34.114+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
