[2025-05-03T21:46:33.081+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gold_pipeline.extract_gold_data manual__2025-05-03T21:46:30.017899+00:00 [queued]>
[2025-05-03T21:46:33.090+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gold_pipeline.extract_gold_data manual__2025-05-03T21:46:30.017899+00:00 [queued]>
[2025-05-03T21:46:33.091+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-03T21:46:33.104+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_gold_data> on 2025-05-03 21:46:30.017899+00:00
[2025-05-03T21:46:33.112+0000] {standard_task_runner.py:57} INFO - Started process 913 to run task
[2025-05-03T21:46:33.116+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gold_pipeline', 'extract_gold_data', 'manual__2025-05-03T21:46:30.017899+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp96lqxu_i']
[2025-05-03T21:46:33.119+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask extract_gold_data
[2025-05-03T21:46:33.181+0000] {task_command.py:415} INFO - Running <TaskInstance: gold_pipeline.extract_gold_data manual__2025-05-03T21:46:30.017899+00:00 [running]> on host 889058e2ea92
[2025-05-03T21:46:33.255+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gold_pipeline' AIRFLOW_CTX_TASK_ID='extract_gold_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T21:46:30.017899+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T21:46:30.017899+00:00'
[2025-05-03T21:46:34.550+0000] {logging_mixin.py:151} INFO - Aperçu des données récupérées :
[2025-05-03T21:46:34.564+0000] {logging_mixin.py:151} INFO -      raw_date source_name  ...  volume         ingestion_timestamp
0  2025-04-03    yfinance  ...   33938  2025-05-03T21:46:34.538743
1  2025-04-03    yfinance  ...   60663  2025-05-03T21:46:34.538860
2  2025-04-03    yfinance  ...  150653  2025-05-03T21:46:34.538937
3  2025-04-03    yfinance  ...   31441  2025-05-03T21:46:34.539010
4  2025-04-03    yfinance  ...    6239  2025-05-03T21:46:34.539089

[5 rows x 7 columns]
[2025-05-03T21:46:35.486+0000] {client.py:496} INFO - Writing to '/gold_datalake/raw/gold_prices/2025-05-03.csv'.
[2025-05-03T21:46:35.562+0000] {util.py:78} ERROR - Exception in child.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/hdfs/util.py", line 76, in consumer
    self._consumer(data)
  File "/home/airflow/.local/lib/python3.8/site-packages/hdfs/client.py", line 515, in consumer
    raise _to_error(res)
hdfs.util.HdfsError: Permission denied: user=hadoop, access=WRITE, inode="/gold_datalake/raw/gold_prices":root:supergroup:drwxr-xr-x
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:399)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:255)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:193)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1879)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1863)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkAncestorAccess(FSDirectory.java:1822)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.resolvePathForStartFile(FSDirWriteFileOp.java:323)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFileInt(FSNamesystem.java:2489)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFile(FSNamesystem.java:2433)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.create(NameNodeRpcServer.java:791)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:475)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)

[2025-05-03T21:46:35.569+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_gold.py", line 79, in extract_gold_data
    x.to_csv(writer, index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/hdfs/util.py", line 104, in __exit__
    raise self._err # pylint: disable=raising-bad-type
  File "/home/airflow/.local/lib/python3.8/site-packages/hdfs/util.py", line 76, in consumer
    self._consumer(data)
  File "/home/airflow/.local/lib/python3.8/site-packages/hdfs/client.py", line 515, in consumer
    raise _to_error(res)
hdfs.util.HdfsError: Permission denied: user=hadoop, access=WRITE, inode="/gold_datalake/raw/gold_prices":root:supergroup:drwxr-xr-x
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:399)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:255)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:193)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1879)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1863)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkAncestorAccess(FSDirectory.java:1822)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.resolvePathForStartFile(FSDirWriteFileOp.java:323)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFileInt(FSNamesystem.java:2489)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFile(FSNamesystem.java:2433)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.create(NameNodeRpcServer.java:791)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:475)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)

[2025-05-03T21:46:35.599+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=gold_pipeline, task_id=extract_gold_data, execution_date=20250503T214630, start_date=20250503T214633, end_date=20250503T214635
[2025-05-03T21:46:35.626+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task extract_gold_data (Permission denied: user=hadoop, access=WRITE, inode="/gold_datalake/raw/gold_prices":root:supergroup:drwxr-xr-x
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:399)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:255)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:193)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1879)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1863)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkAncestorAccess(FSDirectory.java:1822)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.resolvePathForStartFile(FSDirWriteFileOp.java:323)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFileInt(FSNamesystem.java:2489)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFile(FSNamesystem.java:2433)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.create(NameNodeRpcServer.java:791)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:475)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
; 913)
[2025-05-03T21:46:35.660+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-03T21:46:35.690+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
