[2025-05-21T10:17:56.412+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gold_news_pipeline.ingest_news manual__2025-05-21T10:17:50.063598+00:00 [queued]>
[2025-05-21T10:17:56.435+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gold_news_pipeline.ingest_news manual__2025-05-21T10:17:50.063598+00:00 [queued]>
[2025-05-21T10:17:56.436+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-21T10:17:56.502+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): ingest_news> on 2025-05-21 10:17:50.063598+00:00
[2025-05-21T10:17:56.551+0000] {standard_task_runner.py:57} INFO - Started process 810 to run task
[2025-05-21T10:17:56.559+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gold_news_pipeline', 'ingest_news', 'manual__2025-05-21T10:17:50.063598+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/news_batch.py', '--cfg-path', '/tmp/tmp13o90vi6']
[2025-05-21T10:17:56.576+0000] {standard_task_runner.py:85} INFO - Job 107: Subtask ingest_news
[2025-05-21T10:17:56.910+0000] {task_command.py:415} INFO - Running <TaskInstance: gold_news_pipeline.ingest_news manual__2025-05-21T10:17:50.063598+00:00 [running]> on host cf1d2898936c
[2025-05-21T10:17:57.576+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gold_news_pipeline' AIRFLOW_CTX_TASK_ID='ingest_news' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T10:17:50.063598+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T10:17:50.063598+00:00'
[2025-05-21T10:17:58.731+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/news_batch.py", line 40, in ingest_news
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 426 Client Error: Upgrade Required for url: https://newsapi.org/v2/everything?q=gold+market+OR+gold+price&apiKey=4cdba65592e54df9bad3aad6361f2d0b&language=en&sortBy=publishedAt&pageSize=100&page=2
[2025-05-21T10:17:58.760+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=gold_news_pipeline, task_id=ingest_news, execution_date=20250521T101750, start_date=20250521T101756, end_date=20250521T101758
[2025-05-21T10:17:58.796+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 107 for task ingest_news (426 Client Error: Upgrade Required for url: https://newsapi.org/v2/everything?q=gold+market+OR+gold+price&apiKey=4cdba65592e54df9bad3aad6361f2d0b&language=en&sortBy=publishedAt&pageSize=100&page=2; 810)
[2025-05-21T10:17:58.818+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-21T10:17:58.868+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
